/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/mechanical_keyboard.glb -t -o src/components/KeyboardModel.tsx 
Author: Urpo (https://sketchfab.com/Urpo)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/mechanical-keyboard-1facc22c744a403dbb3166a2274f78dd
Title: Mechanical Keyboard
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    defaultMaterial: THREE.Mesh
    defaultMaterial_1: THREE.Mesh
    defaultMaterial_2: THREE.Mesh
    defaultMaterial_3: THREE.Mesh
    defaultMaterial_4: THREE.Mesh
    defaultMaterial_5: THREE.Mesh
  }
  materials: {
    ['03___Default']: THREE.MeshStandardMaterial
    ['09___Default']: THREE.MeshStandardMaterial
    ['02___Default']: THREE.MeshStandardMaterial
    ['08___Default']: THREE.MeshStandardMaterial
    ['07___Default']: THREE.MeshStandardMaterial
    ['01___Default']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/mechanical_keyboard.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials['03___Default']} />
          <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials['09___Default']} />
          <mesh geometry={nodes.defaultMaterial_2.geometry} material={materials['02___Default']} />
          <mesh geometry={nodes.defaultMaterial_3.geometry} material={materials['08___Default']} />
          <mesh geometry={nodes.defaultMaterial_4.geometry} material={materials['07___Default']} />
          <mesh geometry={nodes.defaultMaterial_5.geometry} material={materials['01___Default']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/mechanical_keyboard.glb')
